name: create-release

on:
  workflow_call:
    inputs:
      branch:
        description: 'Name of the branch to release to'
        default: 'main'
        required: false
        type: string
    secrets:
      token:
        description: 'GitHub secret token provided by runner'
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      release_tag:
        description: 'The first output string'
        value: ${{ jobs.release_create.outputs.ReleaseTag }}

jobs:
  release_create:
    permissions:
      contents: write  # need this permission to publish release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # need this for all history for all branches and tags
      - name: Create Release
        id: create_release
        uses: nickatnight/releases-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          branch: ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

    outputs:
      ReleaseTag: ${{ steps.create_release.outputs.release_tag }}
