name: main

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/create-release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
